name: CraftersQuest
version: '1.0'
main: io.github.wamel04.crafters_quest.CraftersQuestPlugin
api-version: '1.20'
author: "WaMel_"
description: "Quest Plugin for Crafters"
depend:
  - ProtocolLib

commands:
  q:
    description: "현재 진행 중인 퀘스트 목록을 확인합니다."
  quest:
    description: "현재 진행 중인 퀘스트 목록을 확인합니다."
  퀘스트:
    description: "현재 진행 중인 퀘스트 목록을 확인합니다."

  pq:
    description: "클리어한 퀘스트 목록을 확인합니다."
  pquest:
    description: "클리어한 퀘스트 목록을 확인합니다."
  이전퀘스트:
    description: "클리어한 퀘스트 목록을 확인합니다."

  getqueststate:
    description: "플레이어의 퀘스트 상태를 확인합니다."
  setqueststate:
    description: "플레이어의 퀘스트 상태를 설정합니다."

  questitem:
    description: "등록된 퀘스트 아이템의 목록을 확인합니다."
  qitem:
    description: "등록된 퀘스트 아이템의 목록을 확인합니다."
  qi:
    description: "등록된 퀘스트 아이템의 목록을 확인합니다."

  registerquestitem:
    description: "들고 있는 아이템을 퀘스트 아이템 목록에 등록합니다."
  rqitem:
    description: "들고 있는 아이템을 퀘스트 아이템 목록에 등록합니다."
  rqi:
    description: "들고 있는 아이템을 퀘스트 아이템 목록에 등록합니다."

  qreload:
    description: "config와 커스텀 파일들을 다시 불러옵니다."
  questreload:
    description: "config와 커스텀 파일들을 다시 불러옵니다."